import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publishableKey= process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
const afterSignout= process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    
    <html
    lang="en"
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
        <ClerkProvider>
      <body className="bg-slate-50 text-slate-900 overflow-x-hidden">{children}</body>
      </ClerkProvider>
    </html>
  );
}
